from .Player import Player
from .Scores import Scores
from .Player2 import Player2
from .Window import Window
from .Desk import Desk
from .LongDesk import LongDesk
from .Door import Door
from .Shelf import Shelf
from .Bookcase import Bookcase
from .ScoresGirl import ScoresGirl
from .ScoresBoy import ScoresBoy
